---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "backend-{{ .Values.appVersion}}"
  namespace: "{{ .Values.namespace }}"
  labels:
    app: backend
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          ports:
            - containerPort: 9000
          env:
            - name: DATABASE_URL
              value: "postgres://postgres:postgres@postgres-{{ .Values.appVersion}}.{{ .Values.namespace }}.svc.cluster.local:5432/news"
