---
apiVersion: v1
kind: Namespace
metadata:
  name: stage
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stage
  namespace: stage
  labels:
    app: stage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stage
  template:
    metadata:
      labels:
        app: stage
    spec:
      containers:
        - name: frontend
          image: nginx
          volumeMounts:
            - mountPath: "/folder"
              name: my-volume
        - name: backend
          image: busybox
          command: ["sleep", "3600"]
          volumeMounts:
            - mountPath: "/folder1"
              name: my-volume
      volumes:
          - name: my-volume
            emptyDir: {}

