---
apiVersion: v1
kind: Pod
metadata:
  name: test1
  labels:
    app: multitool
    p: t1
spec:
  containers:
  - name: tool1
    image: praqma/network-multitool
    env:
         - name: HTTP_PORT
           value: "1180"
         - name: HTTPS_PORT
           value: "11443"
    ports:
         - containerPort: 1180
           name: http-port
         - containerPort: 11443
           name: https-port
---
apiVersion: v1
kind: Pod
metadata:
  name: test2
  labels:
    app: multitool
    p: t2
spec:
  containers:
  - name: tool2
    image: praqma/network-multitool
    env:
         - name: HTTP_PORT
           value: "1180"
         - name: HTTPS_PORT
           value: "11443"
    ports:
         - containerPort: 1180
           name: http-port
         - containerPort: 11443
           name: https-port