kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: "postgres-claim-prod-{{ .Values.appVersion}}"
  namespace: "{{ .Values.namespace }}"
  labels:
    app: postgres
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi


