
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: "db-{{ .Values.appVersion}}"
  namespace: "{{ .Values.namespace }}"
  labels:
    app: db
spec:
  serviceName: "postgres"
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - image: postgres:13-alpine
          name: db
          env:
            - name: POSTGRES_DB
              value: news
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_USER
              value: postgres
            - name: PGDATA
              value: /data/pgdata
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: "postgres-pv-prod-{{ .Values.appVersion}}"
              mountPath: /data
      volumes:
      - name: "postgres-pv-prod-{{ .Values.appVersion}}"
        persistentVolumeClaim:
          claimName: "postgres-claim-prod-{{ .Values.appVersion}}"
