frontend:

  replicaCount: 1
  
  image:
    repository: ssergeya/frontend
    pullPolicy: IfNotPresent
    tag: "1.0.5"
backend:

  replicaCount: 1
  image:
    repository: ssergeya/backend
    npullPolicy: IfNotPresent
    tag: "1.0.5"

appVersion: "3"
namespace: "default"
  

