---
clickhouse:
  hosts:
    clickhouse-01:
      ansible_host: 51.250.18.11
lighthouse:
  hosts:
    lighthouse-01:
      ansible_host: 51.250.25.38
vector:
  hosts:
    vector-01:
      ansible_host: 158.160.15.37